#!/bin/bash

lock_cmd() {
  # Use image as background if it exists, else color
  local bgarg bgimg="${CONFIG_DIR}/lock.png"
  [[ -e "${bgimg}" ]] && bgarg="--image=${bgimg}" || bgarg="--color=000000"

  # Lock the screen
  i3lock \
    --ignore-empty-password \
    --nofork \
    --no-unlock-indicator \
    "${bgarg}"

  # Reload bg
  "${HOME}/.fehbg"
}
