#! /bin/sh

# Set default cursor to pointer
xsetroot -cursor_name left_ptr

# Set background
if [ -r "${HOME}/pictures/bg.png" ]; then
  feh --bg-center "${HOME}/pictures/bg.png"
fi

sxhkd &
compton --daemon

bspc config border_width         2
bspc config window_gap           18

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config normal_border_color         "#303030"
bspc config active_border_color         "#343434"
bspc config focused_border_color        "#343434"
bspc config urgent_border_color         "#a54242"
bspc config focused_locked_border_color "#b294bb"
bspc config presel_feedback_color       "#343434"

bspc config remove_disabled_monitor true
bspc monitor -d I II III IV V VI VII VIII IX X
