#!/usr/bin/env sh

# Display the current terminal color scheme

main() {
  for off in 0 8; do
    for bld in '' '1;'; do
      [ -z $bld ] && printf "norm " || printf "bold "
      printf "%X-%X " "$((0 + off))" "$((7 + off))"
      for col in $(seq 8); do
        printf "\e[%s38;5;%dm████\e[0m" "${bld}" "$((col + off - 1))"
      done
      echo
    done
  done
}

main "$@"
