#!/usr/bin/env sh

# Display the current terminal color scheme

for off in 0 8; do
  for bld in 0 1; do
    printf "\e[%dm" "${bld}"
    [ $bld -eq 0 ] && printf "norm " || printf "bold "
    printf "%X-%X " "$((0 + off))" "$((7 + off))"
    for col in $(seq 8); do
      printf "\e[48;5;%dm    \e[0m" "$((col + off - 1))"
    done
    echo
  done
done
