#!/bin/bash

# Wrapper around i3lock

show_help() {
cat << EOF
Usage: lockscreen [option]

Options:
  -s    suspend to RAM
EOF
}

dunstctl() {
  # Don't do anything unless dunst and notify-send are present
  if [[ ! ( $(command -v dunst) && $(command -v notify-send) ) ]]; then
    return 1
  fi

  if [[ "$1" == "pause" ]]; then
    notify-send "DUNST_COMMAND_PAUSE"
  elif [[ "$1" == "resume" ]]; then
    notify-send "DUNST_COMMAND_RESUME"
  fi
}

main() {
  local suspend="false"

  if [[ ! $(command -v i3lock) ]]; then
    echo "This wrapper script relies on i3lock"
    show_help
    exit 0
  fi

  OPTIND=1
  while getopts "sh" opt; do
    case "${opt}" in
      s)
        suspend="true"
        ;;
      h)
        show_help
        exit 0
        ;;
      \?)
        echo "Invalid option -${OPTARG}"
        show_help
        exit 0
        ;;
    esac
  done
  shift $((OPTIND-1))
  [[ "$1" == "--" ]] && shift

  # Pause dunst notifications
  dunstctl pause

  # Lock screen
  (i3lock -enui "${HOME}/pictures/lock.png" && dunstctl resume) &

  # Optionally suspend
  [[ "${suspend}" == "true" ]] && systemctl suspend
}

main "$@"
