#!/bin/bash

# Wrapper around i3lock

show_help() {
cat << EOF
Usage: lockscreen [option]

Options:
  -s    suspend to RAM
EOF
}

cleanup() {
  # Reset monitor power saving (screen blanking)
  xset dpms 0 0 0

  # Resume dunst notifications
  dunstctl resume
}

lock() {
  # Clean up if killed
  trap cleanup SIGHUP SIGINT SIGTERM

  # Pause dunst notifications
  dunstctl pause

  # Blank screen after 20 seconds
  xset +dpms dpms 20 20 20

  # Lock the screen
  i3lock \
    --ignore-empty-password \
    --nofork \
    --no-unlock-indicator \
    --image="${HOME}/pictures/lock.png"

  cleanup
}

dunstctl() {
  # Don't do anything unless dunst and notify-send are present
  [[ ! ( $(command -v dunst) && $(command -v notify-send) ) ]] && return

  if [[ "$1" == "pause" ]]; then
    notify-send "DUNST_COMMAND_PAUSE"
  elif [[ "$1" == "resume" ]]; then
    notify-send "DUNST_COMMAND_RESUME"
  fi
}

main() {
  local suspend="false"

  if [[ ! $(command -v i3lock) ]]; then
    echo "This wrapper script relies on i3lock"
    show_help
    exit 0
  fi

  OPTIND=1
  while getopts "sh" opt; do
    case "${opt}" in
      s)
        suspend="true"
        ;;
      h)
        show_help
        exit 0
        ;;
      \?)
        echo "Invalid option -${OPTARG}"
        show_help
        exit 0
        ;;
    esac
  done
  shift $((OPTIND-1))
  [[ "$1" == "--" ]] && shift

  lock &

  # Optionally suspend
  [[ "${suspend}" == "true" ]] && systemctl suspend
}

main "$@"
